Unit testing modifications
Project-Epsilon/mobile pull request #16
Opened 2017-02-27 08:40 UTC by ronnpang1

Added unit tests for provider classes

2017-03-05 04:33 UTC, JTalarico requested changes
Please fix the changes regarding comment style.

2017-03-05 04:33 UTC, JTalarico commented on src/providers/bank.service.spec.ts
> +//check deposit
No in-function comments.

2017-03-05 04:33 UTC, JTalarico commented on src/providers/bank.service.spec.ts
> +    //check if deposit is not null
Same. No in-function comments.

2017-03-05 04:33 UTC, JTalarico commented on src/providers/currency.service.spec.ts
> +//currency service test
Use Javadoc style header.

/**
 *
**/

2017-03-05 04:33 UTC, JTalarico commented on src/providers/wallet.service.spec.ts
> +
Needs header describing the function.

2017-03-06 16:39 UTC, ghiobi commented
@ronnpang1 Please make the changes and change the base. Pull request has been open for 7 days.

2017-03-06 22:38 UTC, ghiobi requested changes
Please make the changes.

2017-03-06 22:38 UTC, ghiobi commented on .project
> +<projectDescription>
Please remove file.

2017-03-06 22:38 UTC, ghiobi commented on .settings/.jsdtscope
> +	<classpathentry kind="con" path="org.eclipse.wst.jsdt.launching.JRE_CONTAINER"/>
Please remove file.

2017-03-06 22:38 UTC, ghiobi commented on .settings/org.eclipse.wst.common.project.facet.core.xml
> +  <installed facet="webclipse.typescript" version="1.0"/>
Please remove file.

2017-03-06 22:38 UTC, ghiobi commented on .settings/org.eclipse.wst.jsdt.ui.superType.container
> +org.eclipse.wst.jsdt.launching.JRE_CONTAINER
Please remove file.

2017-03-06 22:38 UTC, ghiobi commented on .settings/org.eclipse.wst.jsdt.ui.superType.name
> +Global
Please remove file.

2017-03-06 22:38 UTC, ghiobi commented on src/providers/auth.service.spec.ts
> +import {AuthService} from './auth.service';
Please add space `{ AuthService }`

2017-03-06 22:38 UTC, ghiobi commented on src/providers/auth.service.spec.ts
> +    beforeEach(() => {
Please fix the spaces.

2017-03-06 22:38 UTC, ghiobi commented on src/providers/bank.service.spec.ts
> +import {environment} from "../environments/environment";
Please add spaces

2017-03-06 22:38 UTC, ghiobi commented on src/providers/bank.service.spec.ts
> +    });
Please fix the spacing.

2017-03-06 22:38 UTC, ghiobi commented on src/providers/currency.service.spec.ts
> +import {Storage} from "@ionic/storage";
Please fix the spacing

2017-03-06 22:38 UTC, ghiobi commented on src/providers/currency.service.spec.ts
> +        {
please use double spaced indents

2017-03-06 22:38 UTC, ghiobi commented on src/providers/wallet.service.spec.ts
> +import {environment} from "../environments/environment";
Please add spaces .

2017-03-06 22:38 UTC, ghiobi commented on src/providers/wallet.service.spec.ts
> +    });
Bad indentation

2017-03-06 22:38 UTC, ghiobi commented on src/providers/wallet.service.spec.ts
> +describe('Wallet Service', () => {
Needs descriptions in comments

2017-03-07 00:22 UTC, ghiobi requested changes
Please make the following changes.

2017-03-07 00:22 UTC, ghiobi commented on src/providers/wallet.service.spec.ts
> +describe('Wallet Service', () => {
Please add a space between imports and test.

2017-03-07 00:22 UTC, ghiobi commented on src/providers/wallet.service.spec.ts
> +      });
Weird indentation

2017-03-07 00:22 UTC, ghiobi commented on src/providers/wallet.service.spec.ts
> +    });
Weird indentation

2017-03-07 00:22 UTC, ghiobi commented on src/providers/currency.service.spec.ts
> +          {
Weird indentation

2017-03-07 00:22 UTC, ghiobi commented on src/providers/currency.service.spec.ts
> +      ]
Weird indentation

2017-03-07 00:22 UTC, ghiobi commented on src/providers/bank.service.spec.ts
> +  })
Weird indentation

2017-03-07 00:22 UTC, ghiobi commented on src/providers/bank.service.spec.ts
> +    beforeEach(() => {
Weird indentation

2017-03-07 00:22 UTC, ghiobi commented on src/providers/bank.service.spec.ts
> +    beforeEach(() => {
Double space or tab?

2017-03-07 00:27 UTC, closed without merging