Unit tests
Project-Epsilon/mobile pull request #21
Opened 2017-03-06 22:32 UTC by ronnpang1

removed comments
addresses issue #16

2017-03-06 22:40 UTC, ghiobi commented
Please read all my comments in https://github.com/Project-Epsilon/mobile/pull/16. Please do not make a new pull request when fixing issues just push the new changes. Thank you.

2017-03-06 22:40 UTC, ghiobi requested changes
Please read https://github.com/Project-Epsilon/mobile/pull/16. Thank you.

2017-03-06 22:41 UTC, ghiobi commented
Please use version-2.0 as base.

2017-03-07 00:30 UTC, ghiobi requested changes
![image](https://cloud.githubusercontent.com/assets/9327403/23636443/65951c14-02a3-11e7-941e-ca6bc17c3dbe.png)

2017-03-07 00:30 UTC, ghiobi commented on .project
> +<projectDescription>
please remove file.

2017-03-07 00:41 UTC, ghiobi requested changes

2017-03-07 00:41 UTC, ghiobi commented on src/providers/wallet.service.spec.ts
> +    });
Weird indentation

2017-03-07 17:07 UTC, JTalarico requested changes
Please fix the requested changes. Your indentation is weird.

2017-03-07 17:07 UTC, JTalarico commented on src/providers/bank.service.spec.ts
> +  })
Indentation is all over the place in this file.

2017-03-07 17:07 UTC, JTalarico commented on src/providers/currency.service.spec.ts
> +      });
Line 15 - 30 should should be indented better. The code is hard to follow.

2017-03-07 17:12 UTC, ghiobi approved these changes

2017-03-07 17:13 UTC, ghiobi requested changes
Please make the changes.

2017-03-07 17:13 UTC, ghiobi commented on src/providers/wallet.service.spec.ts
> +/**
Why is the tsdoc so far away?

2017-03-17 02:23 UTC, JTalarico approved these changes

2017-03-17 15:11 UTC, Scieon requested changes

2017-03-17 15:11 UTC, Scieon commented on src/providers/bank.service.spec.ts
> +        this.BankTransferService = new BankTransferService();
I seem to be getting compilation errors here, I believe it is non-default constructor.

2017-03-17 17:43 UTC, Scieon approved these changes

2017-03-18 01:36 UTC, ghiobi approved these changes

2017-03-18 01:36 UTC, ghiobi commented
Great Ronnie. After so many attempts to follow instructions, we are proud of you.

2017-03-18 02:15 UTC, merged