OTP implmentation
Project-Epsilon/mobile pull request #26
Opened 2017-03-09 02:18 UTC by ronnpang1

=OTP login page added
-OTP methods to access db in providers

2017-03-09 02:30 UTC, Scieon requested changes

2017-03-09 02:30 UTC, Scieon commented on src/pages/OTP/otp.ts
> +  submitOTPCode(codeNumber)
Add tsdoc for all classes, like what you did for showAuth.

2017-03-09 02:30 UTC, Scieon commented on src/pages/OTP/otp.ts
> +
Some awkward indentation in this function

2017-03-09 02:36 UTC, Scieon requested changes

2017-03-09 02:36 UTC, Scieon commented on .settings/.jsdtscope
> +<?xml version="1.0" encoding="UTF-8"?>
What is this file, do we need it?

2017-03-09 02:36 UTC, Scieon commented on .settings/org.eclipse.wst.common.project.facet.core.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Same comment as above

2017-03-09 02:36 UTC, Scieon commented on .settings/org.eclipse.wst.jsdt.ui.superType.container
> +org.eclipse.wst.jsdt.launching.JRE_CONTAINER
?

2017-03-09 02:40 UTC, ghiobi commented
Sorry @ronnpang1 there are a few things to consider here.
1. Before you always commit please make sure you don't add any necessary files.
2. I think you got the general idea of OTP pretty wrong.
3. First research what is OTP before implementing.
4. Please don't copy code in this project, because that usually doesn't work.

2017-03-14 17:06 UTC, ghiobi commented
@ronnpang1 will you update your changes? If you need help on that, let us know immediately.

2017-03-16 20:37 UTC, ghiobi commented
@ronnpang1 Is this complete? please fix the issues/conflicts you were told to do. If you need help please leave some comments.

2017-03-17 15:14 UTC, ghiobi commented
Pull request https://github.com/Project-Epsilon/mobile/pull/26 will replace this. thank you for your time.

> Success is the result of perfection, hard work, learning from failure, loyalty, and persistence. - Colin Powell

2017-03-17 15:14 UTC, closed without merging