Additional Unit tests
Project-Epsilon/mobile pull request #58
Opened 2017-03-20 02:34 UTC by ronnpang1

-Creation of additional unit tests

2017-03-21 13:21 UTC, ghiobi requested changes
@ronnpang1 Please correct these issues by tonight 8:00 EST.

2017-03-21 13:21 UTC, ghiobi commented on .sonar/report-task.txt
> +projectKey=company:my-application
Please remove this file. `.gitingnore` it.

2017-03-21 13:21 UTC, ghiobi commented on src/app/app.spec.ts
> +import {async, ComponentFixture, TestBed} from "@angular/core/testing";
@ronnpang1 Spaces please.

2017-03-21 13:21 UTC, ghiobi commented on src/pages/home/wallet-header/wallet-header.component.spec.ts
> +import { NavController } from "ionic-angular";
SPACES PLEASE.

2017-03-21 13:21 UTC, ghiobi commented on src/pages/login/login.spec.ts
> +import {BaseRequestOptions, Http, HttpModule, Response, ResponseOptions} from "@angular/http";
SPACES AGAIN.

2017-03-21 13:21 UTC, ghiobi commented on src/pages/manage/deposit/deposit.component.spec.ts
> +import {BankTransferService} from "../../../providers/bank.service";
SPACES PLEASE.

2017-03-21 13:21 UTC, ghiobi commented on src/pages/manage/withdraw/withdraw.component.spec.ts
> +import {NavParams} from "ionic-angular";
SPACES PLEASE.

2017-03-21 13:21 UTC, ghiobi commented on src/pages/send-money/send-money.spec.ts
> + * Created by ronniepang on 2017-03-19.
REMOVE THIS.

2017-03-21 13:21 UTC, ghiobi commented on src/pages/send-money/send-money.spec.ts
> +import {NavParams,AlertController, Loading, LoadingController,ModalController,NavController} from "ionic-angular";
SPACES PLEASE.

2017-03-21 13:21 UTC, ghiobi commented on src/pages/transfers/transfers.spec.ts
> +import {NavParams,AlertController, Loading, LoadingController,ModalController,NavController} from "ionic-angular";
SPACES PLEASE.

2017-03-21 13:21 UTC, ghiobi commented on src/pages/transfers/transfers.spec.ts
> + * Created by ronniepang on 2017-03-19.
REMOVE THIS.

2017-03-23 19:48 UTC, JTalarico commented
"-Creation of additional unit tests"

Next time please specify which unit tests have been added. This is very vague.

2017-03-23 20:40 UTC, Scieon commented on src/pages/manage/deposit/deposit.component.spec.ts
> +import {MyApp} from "../../../app/app.component";
Please refer to comment about spaces splease

2017-03-23 21:12 UTC, JTalarico commented on src/providers/auth.service.ts
> +      this.authHttp.post(environment.server_url + "/api/auth/otp" + ((unlock) ? "/unlock" : ""), data)
Why create a variable for response? Why not just return the Observable immediately?

2017-03-23 22:54 UTC, ghiobi approved these changes

2017-03-23 22:55 UTC, ghiobi requested changes
Please remove your generated comment.

2017-03-26 00:15 UTC, ghiobi approved these changes

2017-03-26 00:16 UTC, merged